<a href="https://colab.research.google.com/github/ArielAlexanderFueres/Inteligencia-Artificial/blob/main/Ariel_Fueres_Numpy_29_10_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**LIBRERIA NUMPY**


In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.26.4


In [4]:
myArray=np.array([1,2,3,4,5])
print(myArray)

[1 2 3 4 5]


In [5]:
print(type(myArray))

<class 'numpy.ndarray'>


In [8]:
print(myArray.shape)
print(myArray[2])
myArray[2]=29
print(myArray)

(5,)
3
[ 1  2 29  4  5]


In [10]:
myArray1=np.array([[1,2,3],[4,5,6]])
print(myArray)
print(myArray1.shape)


[ 1  2 29  4  5]
(2, 3)


In [11]:
myArray3=np.zeros((5,5))
print(myArray3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
myArray4=np.full((3,6),10)
print(myArray4)
myArray5=np.eye(5)
print(myArray5)
myArray6=np.ones((5,5))
print(myArray6)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
myArray7=np.random.random((5,5))
print(myArray7)

[[0.89023863 0.64863509 0.81984091 0.42240852 0.89089984]
 [0.03968668 0.4768498  0.13058655 0.66913869 0.57066548]
 [0.96938586 0.02200032 0.10339436 0.95904833 0.67673421]
 [0.35183802 0.00801915 0.19895723 0.29368648 0.85389775]
 [0.6492809  0.16021409 0.85910483 0.56694782 0.67968431]]


In [17]:
myArray8=np.random.randint(100,size=(5,5))
print(myArray8)

[[67 44 75  4 29]
 [11 83 55 38 69]
 [55 47 31 82 29]
 [ 7 55 10 68 53]
 [23 12 18 68 96]]


In [18]:
newMatrix=myArray8[:2,:2]
print(newMatrix)

[[67 44]
 [11 83]]


In [19]:
myArray8[2,2]=10000
print(myArray8)

[[   67    44    75     4    29]
 [   11    83    55    38    69]
 [   55    47 10000    82    29]
 [    7    55    10    68    53]
 [   23    12    18    68    96]]


In [20]:
print(myArray8[2,:])

[   55    47 10000    82    29]


In [21]:
print(myArray8[:,2])

[   75    55 10000    10    18]


In [23]:
print(myArray8[:,2].shape)

(5,)


In [24]:
newMatrix=myArray8[1:4,1:4]
print(newMatrix)

[[   83    55    38]
 [   47 10000    82]
 [   55    10    68]]
