<a href="https://colab.research.google.com/github/ArielAlexanderFueres/Inteligencia-Artificial/blob/main/Ariel_Fueres_5_11_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#
import numpy as np
matrixA=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matrixA.shape)

(3, 4)


In [4]:
matrixA

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
print(matrixA[1:,1:3])

[[ 6  7]
 [10 11]]


In [15]:

matrix = np.random.randint(0, 10, size=(4, 3))
print(matrix)

[[2 0 5]
 [3 6 5]
 [9 7 2]
 [3 7 8]]


In [16]:
print(matrix)
col_indices=np.array([0,1,2])
row_indices=np.array([1,2])

for row,col in zip(row_indices,col_indices):
    #print(row,"-",col)
    print(matrix[row,col])

[[2 0 5]
 [3 6 5]
 [9 7 2]
 [3 7 8]]
3
7


In [17]:
mask=matrix>5
print(mask)

[[False False False]
 [False  True False]
 [ True  True False]
 [False  True  True]]


In [18]:
print(matrix[mask])

[6 9 7 7 8]


In [19]:
print(matrix[matrix>5])

[6 9 7 7 8]


In [20]:
print(matrix)

[[2 0 5]
 [3 6 5]
 [9 7 2]
 [3 7 8]]


In [21]:
matrix[matrix % 2 == 0] += 100
print(matrix)

[[102 100   5]
 [  3 106   5]
 [  9   7 102]
 [  3   7 108]]


In [23]:
print(matrix)


[[102 100   5]
 [  3 106   5]
 [  9   7 102]
 [  3   7 108]]


In [24]:
mask = (matrix >= 3) & (matrix <= 9)
matrix[mask] += 100
print(matrix)

[[102 100 105]
 [103 106 105]
 [109 107 102]
 [103 107 108]]


In [30]:
filter = (matrix > 3) & (matrix < 9)
matrix[filter] += 100
print(matrix)


[[102 100 105]
 [103 106 105]
 [109 107 102]
 [103 107 108]]


In [33]:
matrixA1 = np.random.randint(0, 10, size=(4, 3))
matrixA2 = np.random.randint(0, 10, size=(4, 3))
print("MatrixA1")
print(matrixA1)
print("MatrixA2")
print(matrixA2)

MatrixA1
[[9 7 6]
 [8 5 3]
 [3 5 2]
 [7 2 6]]
MatrixA2
[[6 1 2]
 [0 1 4]
 [9 7 0]
 [7 8 7]]


In [34]:
print(matrixA1+matrixA2)

[[15  8  8]
 [ 8  6  7]
 [12 12  2]
 [14 10 13]]


In [35]:
print(matrixA1-matrixA2)
print(matrixA1*matrixA2)
print(matrixA1/matrixA2)
print(matrixA1+matrixA2)

[[ 3  6  4]
 [ 8  4 -1]
 [-6 -2  2]
 [ 0 -6 -1]]
[[54  7 12]
 [ 0  5 12]
 [27 35  0]
 [49 16 42]]
[[1.5        7.         3.        ]
 [       inf 5.         0.75      ]
 [0.33333333 0.71428571        inf]
 [1.         0.25       0.85714286]]
[[15  8  8]
 [ 8  6  7]
 [12 12  2]
 [14 10 13]]


<ipython-input-35-0f680d72308d>:3: RuntimeWarning: divide by zero encountered in divide
  print(matrixA1/matrixA2)


In [36]:
print(matrixA1)

[[9 7 6]
 [8 5 3]
 [3 5 2]
 [7 2 6]]


In [37]:
print(np.sqrt(matrixA1))

[[3.         2.64575131 2.44948974]
 [2.82842712 2.23606798 1.73205081]
 [1.73205081 2.23606798 1.41421356]
 [2.64575131 1.41421356 2.44948974]]


In [39]:
matrixA1 = np.random.randint(0, 10, size=(2, 5))
print(matrixA1)

[[6 4 6 0 6]
 [7 3 3 9 0]]


In [40]:
print(np.mean(matrixA1))

4.4


In [41]:
print(matrixA1.mean(axis=1))

[4.4 4.4]


In [42]:
print(matrixA1.mean(axis=0))

[6.5 3.5 4.5 4.5 3. ]


In [43]:
print(np.std(matrixA1))

2.8


In [44]:
print(np.median(matrixA1))

5.0


In [47]:
print(matrixA1.sum())

44


In [48]:
print(matrixA1.max())

9


In [49]:
print(matrixA1.min())

0


In [50]:
satart=np.zeros((4,3))
print(satart)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [52]:
add_rows=np.array([1,2,3])
print(add_rows.shape)

(3,)


In [53]:
y=satart+add_rows
print(y)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [54]:
print(satart)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [55]:
col_rows=np.array([[1,2,3,4]])
print(col_rows.shape)

(1, 4)


In [60]:
print(col_rows.T)

[[1]
 [2]
 [3]
 [4]]


In [61]:
#col_rows.reshape(4,1)
tmp=col_rows.T
print(tmp)

[[1]
 [2]
 [3]
 [4]]


In [63]:
matrix = np.arange(1, 5).reshape(-1, 1)
matrix = np.repeat(matrix, 3, axis=1)

print(matrix)

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [67]:
start = np.zeros_like(col_rows.T)

print(start)
tmp = col_rows.T
y2 = start + tmp
print(y2)



[[0]
 [0]
 [0]
 [0]]
[[1]
 [2]
 [3]
 [4]]


In [69]:
tmp1=np.array([[1,1],[2,2]])
tmp2=np.array([[3,3],[4,4]])
print(tmp1)
print(tmp2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [70]:
print(np.dot(tmp1,tmp2))

[[ 7  7]
 [14 14]]


In [71]:
print(tmp1.dot(tmp2))

[[ 7  7]
 [14 14]]


In [72]:
y1=np.random.randint(low=2, high=50, size=(2, 2))
y2=np.random.randint(low=2, high=50, size=(2, 2))
print(y1)
print(y2)

[[36 26]
 [47  6]]
[[32 10]
 [21 19]]


In [73]:
np.vstack((y1,y2))

array([[36, 26],
       [47,  6],
       [32, 10],
       [21, 19]])

In [74]:
np.hstack((y1,y2))

array([[36, 26, 32, 10],
       [47,  6, 21, 19]])